// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBezUTKGg-m2DRZIo2_EAskSJT97weJs_4',
    appId: '1:581031532310:web:ec879ebedfbae93ee9a237',
    messagingSenderId: '581031532310',
    projectId: 'rs-booking',
    authDomain: 'rs-booking.firebaseapp.com',
    storageBucket: 'rs-booking.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKISGqT02tTlkhLjbg4EiFcW2slqluLGU',
    appId: '1:581031532310:android:ec4988c4c796942ee9a237',
    messagingSenderId: '581031532310',
    projectId: 'rs-booking',
    storageBucket: 'rs-booking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcz1F07b13Q0RqcgHpMx3vB4c7qjsf0eA',
    appId: '1:581031532310:ios:f190f5f2c7ee7cd9e9a237',
    messagingSenderId: '581031532310',
    projectId: 'rs-booking',
    storageBucket: 'rs-booking.appspot.com',
    iosClientId: '581031532310-jc5fr7ed8rp3hr0d22nagvt2hoch40ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.rsBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcz1F07b13Q0RqcgHpMx3vB4c7qjsf0eA',
    appId: '1:581031532310:ios:f190f5f2c7ee7cd9e9a237',
    messagingSenderId: '581031532310',
    projectId: 'rs-booking',
    storageBucket: 'rs-booking.appspot.com',
    iosClientId: '581031532310-jc5fr7ed8rp3hr0d22nagvt2hoch40ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.rsBooking',
  );
}
